version: "2"

services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile.dev
    environment:
      DEBUG: "combine.fm*"
      VUE_ENV: server
      DATABASE_URL:
      REDIS_URL:
      GOOGLE_ANDROID_ID:
      GOOGLE_MASTER_TOKEN:
      XBOX_CLIENT_ID:
      XBOX_CLIENT_SECRET:
      YOUTUBE_KEY:
      SPOTIFY_CLIENT_ID:
      SPOTIFY_CLIENT_SECRET:
      AWS_ACCESS_KEY_ID:
      AWS_SECRET_ACCESS_KEY:
      AWS_TAG:
      SLACK_TOKEN:
    volumes:
      - ./:/app:cached
      - node_modules:/app/node_modules
    ports:
      - "3000:3000"
    command: yarn run watch-server
  worker:
    build:
      context: ./
      dockerfile: Dockerfile.dev
    environment:
      DEBUG: "combine.fm*"
      VUE_ENV: server
      DATABASE_URL:
      REDIS_URL:
      GOOGLE_ANDROID_ID:
      GOOGLE_MASTER_TOKEN:
      XBOX_CLIENT_ID:
      XBOX_CLIENT_SECRET:
      YOUTUBE_KEY:
      SPOTIFY_CLIENT_ID:
      SPOTIFY_CLIENT_SECRET:
      AWS_ACCESS_KEY_ID:
      AWS_SECRET_ACCESS_KEY:
      AWS_TAG:
    volumes:
      - ./:/app:cached
      - node_modules:/app/node_modules
    command: yarn run watch-worker
    ports:
      - "3001:3000"
  database:
    image: "postgres:10-alpine"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: "password"
      POSTGRES_USER: "combinefm"
      POSTGRES_DB: "combinefm"
  redis:
    image: "redis:4.0.2-alpine"

volumes:
  node_modules:
