name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build image
      run: |
        docker-compose build
    - name: Test image
      run: make test
      env: 
        COMPOSE_FILE: docker-compose.test.yml
